# This TOML file uses Chunk template engine.
# To use stored variable use {$var}
# The following variables are available:
#    $subreddit -  name of subreddit
#    $author    -  name of author
#    $self_text_html - post selftext as html
#    $flair          - post flair
# all variables declared in this file are also available
# for a full list and other helpful links checkout
# jar.mueed.co.uk
# General settings
[general]
    theme="system" # light dark or system
    upvote="#FFFFBB33"     #aarrggbb
    downvote="#FF33B5E5"   #aarrggbb

# post view on subreddits and frontpage
[posts]
    # format supports limited HTML
    title="<h4>{$title}</h4>"
    format="""\
    <small><a href='/r/{$subreddit}'>r/{$subreddit}</a> \
    {$posts.sep}\
    <a href='/u/{$author}'>u/{$author}</a> </small>\
    """
    sep="🇵🇰"

[comments]
    body="""<h6><a href='/u/$username'>$username</a></h6>\
    <p>
    """